export const links = [
  {
    id: 1,
    name: "SketchUp for Desktop",
    para: "SketchUp for Desktop is the most intuitive way to design, document, and communicate your ideas in 3D.",
    btn1: "Easy to Use",
    btn2: "Multi-Phase Tool",
    content: {
      name: "SKETCHUP PRO",
      heading: "Simple is powerful.",
      para: "The most intuitive way to design, document and communicate your ideas in 3D. SketchUp enables you to design, define, and plan in all stages of the project. Work through your ideas in 3D space and quickly develop your projects. Accuracy from the beginning is key.",
      img: "/sketchup-pro.png ",
    },
  },
  {
    id: 2,
    name: "Extension Warehouse",
    para: "Your library of custom third-party extensions created to optimize your SketchUp workflow.",
    btn1: "Open Source",
    btn2: "Optimization Tool",
    content: {
      name: "EXTENSION WAREHOUSE",
      heading: "Your go-to optimization tool.",
      para: "Extension Warehouse lets you pick a modeling pain point or select your industry, and get a list of extensions that can make your workflow easier. Download and conquer: Any extension you download from the Extension Warehouse will integrate directly in SketchUp Pro.",
      img: "/extension-warehouse.png",
    },
  },
  {
    id: 3,
    name: "SketchUp for iPad",
    para: "SketchUp for iPad has arrived! Design on-site, on the go, and on the couch.",
    btn1: "Easy to Use",
    btn2: "On The Go Tool",
    content: {
      name: "SKETCHUP FOR IPAD",
      heading: "Work anywhere. Create anything. Simple.",
      para: "SketchUp & iPad Pro — together at last. With support for Apple Pencil, multi-touch, and of course, mouse and keyboard, you can harness the power of 3D by drawing, swiping, and clicking to help sketch your creative genius.",
      img: "/sketchup-for-ipad.png",
    },
  },
  {
    id: 4,
    name: "PreDesign",
    para: "Get the valuable data you need to weave contextual insights into your project and get your creative juices flowing before you launch into 3D.",
    btn1: "Conceptual Design",
    btn2: "Research Tool",
    content: {
      name: "PREDESIGN",
      heading: "Enhance your design research.",
      para: "Start your design project in the right direction with PreDesign. Avoid rework during schematic design by focusing only on feasible approaches, quickly access all the graphics and talking points you need to introduce climate factors early, and make a clear case to clients and colleagues for a winning concept.",
      img: "/predesign.png",
    },
  },
  {
    id: 5,
    name: "LayOut",
    para: "LayOut helps you show your client or partner that you’ve captured what you have discussed, and move the project forward confidently.",
    btn1: "2D Communication",
    btn2: "Construction Tool",
    content: {
      name: "LAYOUT",
      heading: "Take your 3D model into 2D space.",
      para: "LayOut and SketchUp Pro are designed to work together. After you insert a SketchUp model into a LayOut document, you can design the document to highlight your 3D model's best features. If you ever need to change or update your original SketchUp model, you can update the model in LayOut so that all the details are synched automatically.",
      img: "/layout.png",
    },
  },
  {
    id: 6,
    name: "SketchUp Viewer",
    para: "See the design in the space it would be built, and get buy-in from clients before you even get permits.",
    btn1: "Post-Production Tool",
    btn2: "On The Go Tool",
    content: {
      name: "SKETCHUP VIEWER",
      heading: "Your models. Anywhere you are.",
      para: "Get work done on the go. You can open .SKP files from anywhere — wherever you are. Present conversational details of your models when you show scenes, layers and views — right on your mobile device. Immerse yourself in the project. Experience your design, so you can understand the project better — its challenges and successes.",
      img: "/sketchup-viewer.png",
    },
  },
  {
    id: 7,
    name: "Sefaira",
    para: "Analyze energy use, daylighting, occupant thermal comfort, and HVAC system sizing during conceptual and schematic design.",
    btn1: "Analytics",
    btn2: "Collaboration Tool",
    content: {
      name: "SAFAIRA",
      heading: "The metrics you need.",
      para: "Sefaira is a concept and schematic design game-changer. Model simple geometry in SketchUp, run analysis to get your first results within minutes, and share proposals using easy-to-understand graphics. Understand your design’s impact on energy cost and CO2 emissions while also measuring the potential impact of a renewable system.",
      img: "/sefaira.png",
    },
  },
  {
    id: 8,
    name: "SketchUp for Schools",
    para: "Browser-based SketchUp for Primary and Secondary schools signed up with Google Workspace for Education or Microsoft Education.",
    btn1: "Easy to Use",
    btn2: "Student Success Tool",
    content: {
      name: "SKETCHUP FOR SCHOOLS",
      heading: "What is SketchUp for Schools?",
      para: "SketchUp for Schools is the core SketchUp modeler now available in a web browser for any Primary or Secondary School signed up with Google Workspace for Education or Microsoft Education. Integrated with Google Drive and Microsoft OneDrive, SketchUp for Schools works on Chromebooks or any Internet-connected computer.",
      img: "/sketchup-for-schools.png",
    },
  },
];
